#! /bin/sh
bspc rule -r "*"
~/.config/polybar/./launch.sh
sxhkd &
picom --experimental-backends &
polybar example &
bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         0
bspc config window_gap          10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config bottom_padding 0
bspc config top_padding 5
feh --bg-fill $HOME/.wallpapers/abc.jpg &
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color1    5"
bspc config presel_feedback_color "$color    1"
bspc config focus_follows_pointer true
bspc rule -a Pavucontrol state=floating rectangle 200x200 sticky=off
xsetroot -cursor_name left_ptr & 
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled" 1
bspc config border_radius 16
/home/angel/.config/bspwm/autostart &
