#!/usr/bin/env bash

## Author  : Aditya Shakya
## Mail    : adi1090x@gmail.com
## Github  : @adi1090x
## Twitter : @adi1090x

style="$($HOME/.config/rofi/applets/menu/style.sh)"

dir="$HOME/.config/rofi/applets/menu/configs/$style"
rofi_command="rofi -theme /home/angel/.rofi-themes/runnerforquick.rasi"

# Error msg
msg() {
	rofi -theme "/home/angel/.rofi-themes/runnerforscrot.rasi" -e "$1"
}

# Browser
if [[ -f /usr/bin/firefox ]]; then
	app="vivaldi-stable"
elif [[ -f /usr/bin/chromium ]]; then
	app="chromium"
elif [[ -f /usr/bin/midori ]]; then
	app="midori"
else
	msg "No suitable web browser found!"
	exit 1
fi

# Links
google="  Search on Google"
facebook="  Facebook"
twitter="  Twitter"
github="  Github"
mail="  Gmail"
youtube="  Youtube"
tinder="  Tinder"

# Variable passed to rofi
options="$google\n$facebook\n$twitter\n$github\n$mail\n$youtube\n$tinder"

chosen="$(echo -e "$options" | $rofi_command -p "Open In  :  $app" -dmenu -selected-row 0 -theme /home/angel/.rofi-themes/runnerforwifi.rasi)"
case $chosen in
    $google)
        $app https://www.google.com &
        ;;
    $facebook)
        $app https://www.facebook.com &
        ;;
    $twitter)
        $app https://www.twitter.com &
        ;;
    $github)
        $app https://www.github.com &
        ;;
    $mail)
        $app https://www.gmail.com &
        ;;
    $youtube)
        $app https://www.youtube.com &
        ;;
    $tinder)
        $app https://www.tinder.com &
esac

