#!/usr/bin/env bash

## Get time and date
TIME="$(date +"%I:%M %p")"
DN=$(date +"%A")
MN=$(date +"%B")
DAY="$(date +"%d")"
MONTH="$(date +"%m")"
YEAR="$(date +"%Y")"
rofi_command="rofi -theme /home/angel/.rofi-themes/runnerfortime.rasi"
options="$DAY\n$MONTH\n$YEAR"


## Main
chosen="$(echo -e "$options" | $rofi_command -p "   $DN, $TIME" -dmenu -selected-row 1)"

